spring:
  application.name: recommendations
security.basic.enabled: false
server.port: 8001
endpoints.health.sensitive: false
eureka:
  instance.hostname: theone
  client.serviceUrl.defaultZone: http://localhost:9000/eureka/